apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cost-qa-addons
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lhs-aws-dep/addons/chart
    targetRevision: maim
    helm: {}
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
