{{- with .Values.argocd_image_updater }}
  {{- if .enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: {{ $.Values.global.argocd_namespace }}
  annotations:
    {{- if .syncwave }}
    argocd.argoproj.io/sync-wave: {{ .syncwave | quote}}
    {{- end }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ $.Values.global.repoURL }}
    targetRevision: master
    path: add-ons/argocd-image-updater
  destination:
    namespace: {{ .namespace }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end }}
  {{- end }}