{{- with .Values.external_dns }}
  {{- if .enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-external-dns
  namespace: {{ $.Values.global.argocd_namespace }}
  annotations:
    {{- if .syncwave }}
    argocd.argoproj.io/sync-wave: {{ .syncwave | quote}}
    {{- end }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ $.Values.global.repoURL }}
    targetRevision: feat/addons/external-dns
    path: main
    helm:
      releaseName: {{.releaseName}}
      valueFiles:
       - values.yaml
  destination:
    namespace: {{ .namespace }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
  {{- end }}